#!/usr/bin/env bash

set -uo pipefail

log_line=20
kind=deployment

dependencies="kubectl jq fzf awk"

display_help() {
  basename "$0"
  echo
  echo "Print previous container logs of selected resource."
  echo
  echo "Usage: " 
  echo " $(basename "$0")"
  echo " $(basename "$0") -h"
  echo " $(basename "$0") -r"
  echo " $(basename "$0") -l 15"
  echo " $(basename "$0") -r -l 15"
  echo
  echo "Flags:"
  echo "  -l number of lines    Default: $log_line"
  echo "  -r kind               Use replicasets to select resource. Default: $kind"
  echo "  -h help               Prints this help"
  echo
  echo "Dependencies:"
  echo
  echo " - kubectl: https://kubernetes.io/docs/tasks/tools/install-kubectl/"
  echo " - jq: https://stedolan.github.io/jq/download/"
  echo " - fzf: https://github.com/junegunn/fzf"
  echo " - awk"

  exit 0
}

check_dependencies() {
  for s in $dependencies; do
    if ! command -v "$s" &> /dev/null; then
      echo "$s is not found and required to run this script."
      exit 1
    fi
  done
}

get_pod_selector() {
  local resource_name
  resource_name=$(echo "$1" | awk '{print $1}')
  local pod_selector
  pod_selector=$(kubectl get "$kind" -o wide "$resource_name" --no-headers | \
    awk '{print $(NF)}')
  echo "$pod_selector"
}

while getopts ":s:l:rh:" o; do
  case "${o}" in
    s)
      log_line=${OPTARG}
      ;;
    r)
      kind=replicasets
      ;;
    l)
      log_line=${OPTARG}
      ;;
    *)
      display_help
      ;;
  esac
done
shift $((OPTIND-1))

check_dependencies

context=$(kubectl config current-context)
namespace=$(kubectl config view --minify --output 'jsonpath={..namespace}')

selected_resource=$(kubectl get $kind | \
  awk '{if ( $2!="0/0" && $2>0 ) print $0}' | \
  fzf --bind 'ctrl-r:reload(kubectl get '"$kind"' | \
    awk '"'"'{if ( $2!="0/0" && $2>0 ) print $0}'"'"')' \
    --cycle --border --prompt $kind'> ' \
    --header="CONTEXT: $context | NAMESPACE: $namespace | (ctrl-r: reload)" \
    --header-lines=1 \
    --preview-window="50%" \
    --preview="echo {} | awk '{print \$1}' | read app; \
      kubectl get $kind -o wide \$app --no-headers | \
      awk '{print \$(NF)}' | read selector; kubectl get po -l=\$selector"
  )

result=$?
if [ $result -eq 0 ]; then
  pod_selector=$(get_pod_selector "$selected_resource")

  restarted_container_count=$(kubectl get pods --no-headers -l="$pod_selector" | \
    awk '{if ($4 > 0) print $1}' | wc -l)

  if [ "$restarted_container_count" -eq 0 ]; then
    echo "There is no restarted pod under selected "$kind""
    exit 0
  fi

  containers_in_pod=$(kubectl get pod -l="$pod_selector" -o json | \
    jq -r '.items[0].spec.containers[].name')
  container_count=$(echo $containers_in_pod | awk -F' ' '{print NF}')

  if [ "$container_count" -gt 1 ]; then
    container=$(kubectl get pod -l="$pod_selector" -o json | \
      jq -r '.items[0].spec.containers[].name' | \
      fzf --cycle --border --prompt 'container> ' \
    )
  else
    container=$containers_in_pod
  fi
  
  result=$?
  if [ $result -eq 0 ]; then
    container=${container// /|}

    for pod in $(kubectl get po --no-headers -l="$pod_selector" | \
      awk '{ if ( $4 > 0 ) print $1}'); do
      echo -e "$pod - $container"
      kubectl logs "$pod" -c "$container" --previous --tail="$log_line"
      echo -e "------------\n"
    done
  fi
else
  echo "bye"
fi
